### ISSUE TITLE
PHP Fatal error on step 4 Auth0 Quickstart Guide

### ISSUE THREAD

**Issue by mexiar** [auth0-samples/auth0-php-web-app#81]
Hi all! This is probably a pretty simple issue, but I’m no expert :/

I’ve been following the Auth0 PHP SDK Quickstarts: Add Login to your PHP application https://auth0.com/docs/quickstart/webapp/php/interactive and on step 4, when configuring and running login.php I receive the following error:

```
PHP Fatal error:  Uncaught Error: Call to a member function login() on null in /home1/queversp/public_html/login.php:11
Stack trace:
#0 {main}
  thrown in /home1/queversp/public_html/login.php on line 11
```

The login.php code is

```
<?php

  declare(strict_types=1);

  /**
   * Prepare application session and redirect to the Auth0 Universal Login page.
   *
   * The user will be redirected to your callback route to complete the authentication flow.
   */

  header(sprintf('Location: %s', $sdk->login()));
```

I don’t know what I’m missing, can anyone help? Thanks!

**Comment by mexiar** [comment]
Found the error: the login.php file I've created only had the exact code that the guide shows, not including the one in index.php. I just included that code before the one in login.php and it worked properly. You should specify that in the guide. Thanks!

**Comment by evansims** [comment]
Hi @mexiar 👋 The code from the written guide and this repository are somewhat different at the moment — sorry for any confusion there. We're working on bringing those into better alignment at the moment.

I've double-checked the written guide, and it does function as written, so I'm not sure why you would not have had the $sdk variable in-scope (resulting in the `null` error.) Perhaps you were mistakenly trying to call `login.php` directly, instead of being routed through `index.php`?

In any event, I'm glad you got it working!
